USE codeup_test_db;
DROP TABLE IF EXISTS albums;
CREATE TABLE albums (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    artist VARCHAR(50) DEFAULT 'NONE',
    name VARCHAR(100) NOT NULL DEFAULT 'ARTIST NAME',
    release_date INT UNSIGNED NOT NULL,
    sales DECIMAL(9, 2) UNSIGNED NOT NULL,
    genre VARCHAR(20) DEFAULT 'GENRE',
    PRIMARY KEY (id)
);